language: java
jdk:
  - oraclejdk7
branches:
  only:
    - master
script: "mvn deploy --settings settings.xml"
notifications:
  email: false
env:
  global:
    - secure: "TQdeoc63WgxPzgMb4K8FIrh/8GDUran7QgD3jHqSPWfMn2GegAlDz61inQQjnYrq396cw+xHjEgMkdtAFENftnQFgz5IdoXtl69bavyIEmf1xmVxtBQgd76zAmCekbLz46PKzdIMdewBUQA4sXfEJ20j04vjm3VdYWBsTIK/F6I="
    - secure: "li9xfg75Kg5u6tCiNgKCAq7xPz1jzY4fqDUwLwKCZ6oyQ3c0NdbRQBwsMZqLm+CQxBAzYwKboJgzF8VCmJCjXYgPEv92lG2M6/yjolCYZ9mCzpKao16R5byuTWN/ycmU1mJNDVAAbsAycyOzASyAp9+WxcBDwRWDS+0zJuhjMtg="
